
"""Add PIN, category, phase, consultation_data, rating, feedback to ChatSession

Revision ID: 20240101000000
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20240101000000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('pin', sa.String(length=6), nullable=True))
    op.add_column('chat_sessions', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('chat_sessions', sa.Column('phase', sa.String(length=50), nullable=True))
    op.add_column('chat_sessions', sa.Column('consultation_data', sa.Text(), nullable=True))
    op.add_column('chat_sessions', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('chat_sessions', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'feedback')
    op.drop_column('chat_sessions', 'rating')
    op.drop_column('chat_sessions', 'consultation_data')
    op.drop_column('chat_sessions', 'phase')
    op.drop_column('chat_sessions', 'category')
    op.drop_column('chat_sessions', 'pin')
    # ### end Alembic commands ###
