# A brief description of your function
name = "thread-summarizer"
# Which directory to deploy to
[deploy]
# Directory where your function code lives
project = "supabase/functions/thread-summarizer"
# Import map for Deno
import_map = "supabase/functions/thread-summarizer/deno.json"

[env]
# Environment variables for your function
# Add any environment variables your function needs here
